name: Deploy to Cloudflare Pages

on:
  push:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    environment:
      name: cloudflare
      url: ${{steps.deploy.outputs.deployment-url}}
    name: Publish to Cloudflare Pages
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm install
      - run: npm run generate-commit-hash
      - run: npm run build --if-present
        env:
          # PUBLIC_URL might not be needed for Cloudflare Pages or handled differently.
          # If fixed base path is needed, Cloudflare Pages has settings for this.
          # Keeping secrets for now, assuming build process might still use them.
          REACT_APP_CLIENT_ID: ${{ secrets.REACT_APP_CLIENT_ID }}
          REACT_APP_CLIENT_SECRET: ${{ secrets.REACT_APP_CLIENT_SECRET }}
      - run: npm test
        # TODO Remove this
        continue-on-error: true # Keeping this as it was in the original file
      - name: Publish to Cloudflare Pages
        id: deploy
        uses: cloudflare/wrangler-action@7a5f8bbdfeedcde38e6777a50fe685f89259d4ca
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 62758afcaaf5e929beeac70e72312bc6
          wranglerVersion: "3"
          command: pages deploy build --project-name emailanalyzer
          # Assuming 'build' is the output directory of 'npm run build'
