name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
      - preview

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Needed for checkout and potentially build scripts
      # No deployment permissions needed for build job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Generate commit hash
        run: npm run generate-commit-hash
      - name: Build application
        run: npm run build --if-present
        env:
          REACT_APP_CLIENT_ID: ${{ secrets.REACT_APP_CLIENT_ID }}
          REACT_APP_CLIENT_SECRET: ${{ secrets.REACT_APP_CLIENT_SECRET }}
      - name: Run tests
        run: npm test
        continue-on-error: true # Keeping this as it was in the original file
      - name: Upload Pages artifact
        uses: actions/upload-artifact@v4
        with:
          name: pages-build
          path: build/ # Assuming 'build' is the output directory
          retention-days: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read # May be needed by wrangler or if any checkout is done; safer to include.
      deployments: write # Required for Cloudflare Pages deployment
    environment:
      name: cloudflare
      url: ${{steps.deploy.outputs.deployment-url}} # Wrangler action provides this output
    name: Publish to Cloudflare Pages # Job name
    steps:
      - name: Download Pages artifact
        uses: actions/download-artifact@v4
        with:
          name: pages-build
          path: build/ # Download the artifact to 'build/' directory
      - name: Publish to Cloudflare Pages
        id: deploy # Step ID for environment URL output
        uses: cloudflare/wrangler-action@7a5f8bbdfeedcde38e6777a50fe685f89259d4ca
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 62758afcaaf5e929beeac70e72312bc6
          wranglerVersion: "3"
          # Command will run in the root, ensure 'build' dir is at this level after download
          command: pages deploy --no-bundle --project-name emailanalyzer --directory build --branch ${{ github.ref_name }}
